# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../dataLevel/datamanager.h \
    ../../dataLevel/dataComm/IfDataComm.h \
    ../../dataLevel/dataComm/sharemem/FileBase.h \
    ../../dataLevel/dataComm/sharemem/ipcSharemem.h \
    ../../dataLevel/dataComm/sharemem/sharemem.h \
    ../../dataLevel/dataComm/sysipc/message.h \
    ../../dataLevel/dataComm/sysipc/strings.h \
    ../../dataLevel/dataComm/sysipc/sysipc.h \
    ../../dataLevel/dataComm/inc/basedef.h \
    ../../dataLevel/dataComm/inc/stdinclude.h \
    ../../dataLevel/dataComm/inc/typedef.h \
    ../../dataLevel/CardStateMgr/CardStateManager.h
SOURCES += ../../dataLevel/datamanager.cpp \
    ../../dataLevel/dataComm/IfDatacomm.cpp \
    ../../dataLevel/dataComm/sharemem/FileBase.cpp \
    ../../dataLevel/dataComm/sharemem/ipcSharemem.cpp \
    ../../dataLevel/dataComm/sharemem/sharemem.cpp \
    ../../dataLevel/dataComm/sysipc/message.cpp \
    ../../dataLevel/dataComm/sysipc/strings.cpp \
    ../../dataLevel/dataComm/sysipc/sysipc.cpp \
    ../../dataLevel/CardStateMgr/CardStateManager.cpp
