#×Ü¿ØMakefile

everything :
	$(MAKE) everything -C share
	$(MAKE) everything -C mpcfg
	$(MAKE) everything -C dbcj
	$(MAKE) everything -C httx
	$(MAKE) everything -C lcd
	$(MAKE) everything -C ppp
	$(MAKE) everything -C jlcy
	$(MAKE) everything -C fhkz
	$(MAKE) everything -C ctcy
	$(MAKE) everything -C rftx
	$(MAKE) everything -C main

clean :
	$(MAKE) clean -C share
	$(MAKE) clean -C mpcfg
	$(MAKE) clean -C dbcj
	$(MAKE) clean -C httx
	$(MAKE) clean -C lcd
	$(MAKE) clean -C ppp
	$(MAKE) clean -C jlcy
	$(MAKE) clean -C fhkz
	$(MAKE) clean -C ctcy
	$(MAKE) clean -C rftx
	$(MAKE) clean -C main

veryclean :
	$(MAKE) veryclean -C share
	$(MAKE) veryclean -C mpcfg
	$(MAKE) veryclean -C dbcj
	$(MAKE) veryclean -C httx
	$(MAKE) veryclean -C lcd
	$(MAKE) veryclean -C ppp
	$(MAKE) veryclean -C jlcy
	$(MAKE) veryclean -C fhkz
	$(MAKE) veryclean -C ctcy
	$(MAKE) veryclean -C rftx
	$(MAKE) veryclean -C main

rebuild :
	$(MAKE) rebuild -C share
	$(MAKE) rebuild -C mpcfg
	$(MAKE) rebuild -C dbcj
	$(MAKE) rebuild -C httx
	$(MAKE) rebuild -C lcd
	$(MAKE) rebuild -C ppp
	$(MAKE) rebuild -C jlcy
	$(MAKE) rebuild -C fhkz
	$(MAKE) rebuild -C ctcy
	$(MAKE) rebuild -C rftx
	$(MAKE) rebuild -C main

