# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../main/application.h \
    ../../main/common.h \
    ../../main/costctrlterminal.h \
    ../../common_ctrl/inputMoneyWidget.h \
    ../../common_ctrl/reportWidget.h \
    ../../main/utils/keyInput.h \
    ../../main/utils/mThread.h \
    ../../main/utils/publicNotice.h \
    ../../main/utils/splash.h \
    ../../main/content/chargePage.h \
    ../../main/content/managerAndMaintainPage.h \
    ../../main/content/managerMainPage.h \
    ../../main/content/managerParamSettingsPage.h \
    ../../main/content/managerPowerMonitorPage.h \
    ../../main/content/managerSystemMaintenancePage.h \
    ../../main/content/managerSystemParamPage.h \
    ../../main/content/managerTerminalInfoPage.h \
    ../../main/content/userChargeReocrdPage.h \
    ../../main/content/userCurrentElecPage.h \
    ../../main/content/userHistoryElecPage.h \
    ../../main/content/userMainPage.h \
    ../../main/content/userNoticePage.h \
    ../../main/content/userQueryPage.h \
    ../../main/content/userRepay.h
SOURCES += ../../main/application.cpp \
    ../../main/costctrlterminal.cpp \
    ../../main/main.cpp \
    ../../common_ctrl/inputMoneyWidget.cpp \
    ../../common_ctrl/reportWidget.cpp \
    ../../main/utils/keyInput.cpp \
    ../../main/utils/mThread.cpp \
    ../../main/utils/publicNotice.cpp \
    ../../main/utils/splash.cpp \
    ../../main/content/chargePage.cpp \
    ../../main/content/managerAndMaintainPage.cpp \
    ../../main/content/managerMainPage.cpp \
    ../../main/content/managerParamSettingsPage.cpp \
    ../../main/content/managerPowerMonitorPage.cpp \
    ../../main/content/managerSystemMaintenancePage.cpp \
    ../../main/content/managerSystemParamPage.cpp \
    ../../main/content/managerTerminalInfoPage.cpp \
    ../../main/content/userChargeReocrdPage.cpp \
    ../../main/content/userCurrentElecPage.cpp \
    ../../main/content/userHistoryElecPage.cpp \
    ../../main/content/userMainPage.cpp \
    ../../main/content/userNoticePage.cpp \
    ../../main/content/userQueryPage.cpp \
    ../../main/content/userRepay.cpp
FORMS += ../../common_ctrl/inputMoneyWidget.ui
RESOURCES += ./costctrlterminal.qrc
