#×Ü¿ØMakefile

everything :
	$(MAKE) everything -C gz
#end
	$(MAKE) everything -C default

clean :
	$(MAKE) clean -C gz
#end
	$(MAKE) clean -C default

veryclean :
	$(MAKE) veryclean -C gz
#end
	$(MAKE) veryclean -C default

rebuild :
	$(MAKE) rebuild -C gz
#end
	$(MAKE) rebuild -C default

